# Generated by Django 3.2.4 on 2023-09-13 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.IntegerField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nameAlumno', models.CharField(db_column='nameAlumno', max_length=100)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nameGenero', models.CharField(db_column='nameGenero', max_length=100)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Alumno_has_Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Alumno', models.ForeignKey(db_column='fk_Alumno', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_Genero', models.ForeignKey(db_column='fk_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
