# Generated by Django 3.2.4 on 2023-09-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('idGender', models.IntegerField(db_column='idGender', primary_key=True, serialize=False)),
                ('nameGender', models.CharField(db_column='nameGender', max_length=100)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.IntegerField(db_column='idProduct', primary_key=True, serialize=False)),
                ('nameProduct', models.CharField(db_column='nameProduct', max_length=100)),
                ('priceProduct', models.FloatField(db_column='priceProduct', default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(db_column='idRol', primary_key=True, serialize=False)),
                ('nameRol', models.CharField(db_column='nameRol', max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.IntegerField(db_column='idUser', primary_key=True, serialize=False)),
                ('nameUser', models.CharField(db_column='nameUser', max_length=100)),
                ('fk_Gender', models.ForeignKey(db_column='fk_Gender', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.gender')),
                ('fk_Rol', models.ForeignKey(db_column='fk_Rol', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Genero',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Alumno_has_Genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
